### ISSUE TITLE
Error: ENOENT, no such file or directory

### ISSUE THREAD

**Issue by MiroHibler** [meteorhacks/meteor-ssr#43]
Similar to #12, I'm getting `Error: ENOENT, no such file or directory` while running `meteor test-packages` on v1.2.1.

``` sh
W20160311-01:11:20.854(1)? (STDERR) Error: ENOENT, no such file or directory '/private/var/folders/72/_svv01c12bz1ntb2qgjsnvgh0000gn/T/meteor-test-run1x85mkj/.meteor/local/build/programs/web.browser/app'
W20160311-01:11:20.854(1)? (STDERR)     at Object.fs.readdirSync (fs.js:666:18)
W20160311-01:11:20.854(1)? (STDERR)     at readTemplates (packages/meteorhacks_ssr/packages/meteorhacks_ssr.js:121:1)
W20160311-01:11:20.855(1)? (STDERR)     at SSR (packages/meteorhacks_ssr/packages/meteorhacks_ssr.js:114:1)
W20160311-01:11:20.855(1)? (STDERR)     at Package (packages/meteorhacks_ssr/packages/meteorhacks_ssr.js:138:1)
W20160311-01:11:20.855(1)? (STDERR)     at /private/var/folders/72/_svv01c12bz1ntb2qgjsnvgh0000gn/T/meteor-test-run1x85mkj/.meteor/local/build/programs/server/packages/meteorhacks_ssr.js:188:4
W20160311-01:11:20.856(1)? (STDERR)     at /private/var/folders/72/_svv01c12bz1ntb2qgjsnvgh0000gn/T/meteor-test-run1x85mkj/.meteor/local/build/programs/server/packages/meteorhacks_ssr.js:198:3
W20160311-01:11:20.856(1)? (STDERR)     at /private/var/folders/72/_svv01c12bz1ntb2qgjsnvgh0000gn/T/meteor-test-run1x85mkj/.meteor/local/build/programs/server/boot.js:242:10
W20160311-01:11:20.856(1)? (STDERR)     at Array.forEach (native)
W20160311-01:11:20.856(1)? (STDERR)     at Function._.each._.forEach (/Users/miro/.meteor/packages/meteor-tool/.1.1.10.17cq71q++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160311-01:11:20.856(1)? (STDERR)     at /private/var/folders/72/_svv01c12bz1ntb2qgjsnvgh0000gn/T/meteor-test-run1x85mkj/.meteor/local/build/programs/server/boot.js:137:5
```

No problem though while running locally or deployed (with `mup`).

**Comment by jjrasche** [comment]
+1
Edit: After reading [https://github.com/meteorhacks/meteor-ssr/issues/12](#12), I realized I was using an old version v1.0.0. When I speciied V2.2.0, there were no problems.

**Comment by theodorDiaconu** [comment]
+1
