### ISSUE TITLE
Test-packages broken by meteorhacks:ssr

### ISSUE THREAD

**Issue by theodorDiaconu** [meteorhacks/meteor-ssr#46]
W20160425-15:43:46.983(3)? (STDERR)  
W20160425-15:43:46.985(3)? (STDERR) /home/theodor/.meteor/packages/meteor-tool/.1.3.2_4.1l7zi3b++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160425-15:43:46.985(3)? (STDERR)                                             throw(ex);
W20160425-15:43:46.985(3)? (STDERR)                                                   ^
W20160425-15:43:46.986(3)? (STDERR) Error: ENOENT, no such file or directory '/tmp/meteor-test-runq2u59b/.meteor/local/build/programs/web.browser/app'
W20160425-15:43:46.986(3)? (STDERR)     at Object.fs.readdirSync (fs.js:666:18)
W20160425-15:43:46.986(3)? (STDERR)     at readTemplates (packages/meteorhacks_ssr/packages/meteorhacks_ssr.js:121:1)
W20160425-15:43:46.986(3)? (STDERR)     at SSR (packages/meteorhacks_ssr/packages/meteorhacks_ssr.js:114:1)
W20160425-15:43:46.986(3)? (STDERR)     at Package (packages/meteorhacks_ssr/packages/meteorhacks_ssr.js:138:1)
W20160425-15:43:46.987(3)? (STDERR)     at packages/meteorhacks_ssr/packages/meteorhacks_ssr.js:163:1
W20160425-15:43:46.987(3)? (STDERR)     at packages/meteorhacks_ssr/packages/meteorhacks_ssr.js:163:1
W20160425-15:43:46.987(3)? (STDERR)     at /tmp/meteor-test-runq2u59b/.meteor/local/build/programs/server/boot.js:283:10
W20160425-15:43:46.988(3)? (STDERR)     at Array.forEach (native)
W20160425-15:43:46.988(3)? (STDERR)     at Function._.each._.forEach (/home/theodor/.meteor/packages/meteor-tool/.1.3.2_4.1l7zi3b++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160425-15:43:46.988(3)? (STDERR)     at /tmp/meteor-test-runq2u59b/.meteor/local/build/programs/server/boot.js:133:5

**Comment by theodorDiaconu** [comment]
Solution:
mkdir -p /tmp/meteor-test-runq2u59b/.meteor/local/build/programs/web.browser/app
